# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEMScan',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Process')),
                ('image_source', models.CharField(blank=True, choices=[('leo1550', 'LEO 1550'), ('esem_600', 'FEI eSEM'), ('fib_1200', 'FEI Dual-Beam FIB')], default='esem_600', max_length=45, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.process',),
        ),
    ]
