doc-warnings: yes

test-warnings: no

strictness: veryhigh

uses:
    - django

autodetect: yes

requirements:
    - requirements/development.txt
    - requirements/production.txt
    - requirements/testing.txt

ignore-paths:
    - docs

ignore-patterns:
    - (^|/)__init__\.py(/|$)

pep8:
    full: true
    options:
        max-line-length: 100
    disable:
        - E123
        - E127
        - E128
        - E133

pylint:
    disable:  # disable several warnings due to use of Django class-based views
        - W0232  # class has no __init__ method
        - W1202  # use % in logging functions
        - W0613  # unused argument
        - R0903  # too few public methods
        - R0901  # too many ancestors
        - E1002  # super on old style class - disabled due to issue #151
        - D100   # missing docstring in public module
    options:
        max-line-length: 100
