language: python

python:
    - 2.7

services:
    - redis-server
    - postgresql

addons:
    postgresql: "9.4"

env:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=flake

install:
    - pip install tox
    - pip install coveralls
    - npm install -g bower
    - bower install
    - travis_wait tox --notest  # install dependencies

before_script:
    - cp wbg/secrets.travis.json wbg/secrets.json
    - psql -c 'create database travisci;' -U postgres

script:
    - tox

after_success:
    - coveralls

branches:
    only:
        - master
        - develop
