db:
  image: postgres
  ports:
      - "5432:5432"
redis:
  image: redis
  ports:
      - "6379:6379"
app:
  image: emergence/emergence:develop
  command: python3 /opt/emergence/manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/opt/emergence
  ports:
    - "8000:8000"
  environment:
    - DJANGO_SETTINGS_MODULE=wbg.settings.docker
  links:
    - db
    - redis
worker:
  image: emergence/emergence:develop
  command: python3 manage.py rqworker default
  volumes:
    - .:/opt/django
  environment:
    - DJANGO_SETTINGS_MODULE=wbg.settings.docker
  links:
    - db
    - redis
nginx:
  image: nnewman/nginx-extras:latest
  ports:
    - "80:80"
  volumes:
    - ./bin:/etc/nginx/conf.d/
    - ./static:/opt/emergence/static
    - ./media:/opt/emergence/media
  links:
    - app
