db:
  image: postgres
  ports:
      - "5432:5432"
redis:
  image: redis
  ports:
      - "6379:6379"
web:
  image: emergence/emergence:latest
  command: python3 /opt/django/manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/opt/django
  ports:
    - "8000:8000"
  environment:
    - DJANGO_SETTINGS_MODULE=wbg.settings.docker
  links:
    - db
    - redis
worker:
  image: emergence/emergence:latest
  command: python3 manage.py rqworker default
  volumes:
    - .:/opt/django
  environment:
    - DJANGO_SETTINGS_MODULE=wbg.settings.docker
  links:
    - db
    - redis
