db:
  image: postgres
  ports:
      - "5432:5432"
redis:
  image: redis
  ports:
      - "6379:6379"
elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
web:
  build: .
  command: python /opt/django/manage.py runserver 0.0.0.0:8000 --insecure --settings=wbg.settings.docker
  volumes:
    - .:/opt/django
  ports:
    - "8000:8000"
  links:
    - db
    - redis
    - elasticsearch
