# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_processtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocess',
            name='title',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='title',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processtemplate',
            name='title',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
