# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_process_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfigurationDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
