# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:27
from __future__ import unicode_literals

from django.db import migrations

from core.configuration.operations import PublishConfiguration


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_process_title'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        PublishConfiguration('scheduling_type', 'none', choices=[
            'none',
            'simple',
            'full',
            'external',
        ]),
        PublishConfiguration('creation_type', 'default', choices=[
            'default',
            'custom',
        ]),
    ]
