# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


def migrate_legacy_run_date(apps, schema_editor):
    """For old processes, assume run_date should be the value of created."""
    Process = apps.get_model('core', 'Process')

    for process in Process.objects.all():
        process.run_date = process.created
        process.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_process_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocess',
            name='run_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='process',
            name='run_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.RunPython(migrate_legacy_run_date),
    ]
