# Generated by Django 2.1.5 on 2019-01-08 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_process_run_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'process', 'verbose_name_plural': 'processes'},
        ),
        migrations.AlterModelOptions(
            name='processcategory',
            options={'verbose_name': 'process category', 'verbose_name_plural': 'process categories'},
        ),
        migrations.AlterModelOptions(
            name='substrate',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='historicalprocess',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datafiles', related_query_name='datafiles', to='core.Process'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, default='generic-process', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.ProcessType'),
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processnode',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.ProcessNode'),
        ),
        migrations.AlterField(
            model_name='processnode',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Process'),
        ),
        migrations.AlterField(
            model_name='processtemplate',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='category',
            field=models.ForeignKey(default='uncategorized', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processtypes', related_query_name='processtype', to='core.ProcessCategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.Group', verbose_name='member_group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.Group', verbose_name='owner_group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='viewer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.Group', verbose_name='viewer_group'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='process_tree',
            field=mptt.fields.TreeOneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProcessNode'),
        ),
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', related_query_name='task', to='core.Milestone'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
