# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:27
from __future__ import unicode_literals

from django.db import migrations
from core.migration_operations import PublishAppConfiguration


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_app_configuration'),
    ]

    operations = [
        PublishAppConfiguration('scheduling_type', 'none', choices=[
            'none',
            'simple',
            'full',
            'external',
        ]),
        PublishAppConfiguration('creation_type', 'default', choices=[
            'default',
            'custom',
        ]),
    ]
