# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:51
from __future__ import unicode_literals

from django.db import migrations

import core.configuration.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_core_configuration'),
        ('afm', '0002_create_processtype'),
        ('d180', '0002_create_processtype'),
        ('hall', '0002_create_processtype'),
        ('sem', '0002_create_processtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='configuration',
            field=core.configuration.fields.ConfigurationField(default=core.configuration.fields.build_configuration_default),
        ),
    ]
