# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 16:51
from __future__ import unicode_literals

from django.db import migrations

from core.configuration.models import get_configuration_default
from core.configuration.operations import ConfigurationSubscribe


def copy_configuration_forward(apps, schema_editor):
    ProcessType = apps.get_model('core', 'ProcessType')

    for process_type in ProcessType.objects.all():
        process_type.configuration['core_scheduling_type'] = process_type.scheduling_type
        process_type.configuration['core_creation_type'] = process_type.creation_type
        process_type.save()


def copy_configuration_backward(apps, schema_editor):
    ProcessType = apps.get_model('core', 'ProcessType')

    for process_type in ProcessType.objects.all():
        try:
            process_type.scheduling_type = process_type.configuration['core_scheduling_type']
        except KeyError:
            process_type.scheduling_type = get_configuration_default('core_scheduling_type')
        try:
            process_type.creation_type = process_type.configuration['core_creation_type']
        except KeyError:
            process_type.creation_type = get_configuration_default('core_creation_type')
        process_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_processtype_configuration'),
    ]

    operations = [
        ConfigurationSubscribe(
            model_name='processtype',
            field_name='configuration',
        ),
        migrations.RunPython(copy_configuration_forward, copy_configuration_backward),
    ]
