# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 14:58
from __future__ import unicode_literals

from django.db import migrations, models


def copy_uuid_data(apps, schema_editor):
    Process = apps.get_model('core', 'Process')
    ProcessNode = apps.get_model('core', 'ProcessNode')
    HistoricalProcess = apps.get_model('core', 'HistoricalProcess')

    for p in Process.objects.all():
        p.uuid_tmp = str(p.uuid_full)
        p.save()
    for p in ProcessNode.objects.all():
        p.uuid_tmp = str(p.uuid_full)
        p.save()
    for p in HistoricalProcess.objects.all():
        p.uuid_tmp = str(p.uuid_full)
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160413_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocess',
            name='uuid_tmp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='process',
            name='uuid_tmp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='processnode',
            name='uuid_tmp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RunPython(copy_uuid_data),
    ]
