# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:26
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


def copy_uuid_data(apps, schema_editor):
    Process = apps.get_model('core', 'Process')
    ProcessNode = apps.get_model('core', 'ProcessNode')
    HistoricalProcess = apps.get_model('core', 'HistoricalProcess')

    for p in Process.objects.all():
        p.uuid_full = uuid.UUID(p.uuid_tmp)
        p.save()
    for p in ProcessNode.objects.all():
        p.uuid_full = uuid.UUID(p.uuid_tmp)
        p.save()
    for p in HistoricalProcess.objects.all():
        p.uuid_full = uuid.UUID(p.uuid_tmp)
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_old_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocess',
            name='uuid_full',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='process',
            name='uuid_full',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='processnode',
            name='uuid_full',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(copy_uuid_data),
    ]
