# Generated by Django 2.1.5 on 2019-01-08 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d180', '0002_create_processtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d180growthinfo',
            name='platter',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='d180.Platter'),
        ),
        migrations.AlterField(
            model_name='d180recipelayer',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe', to='core.Process'),
        ),
    ]
