# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'operator'
        db.create_table(u'operators', (
            ('id', self.gf('django.db.models.fields.IntegerField')(primary_key=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
        ))
        db.send_create_signal(u'afm_viewer', ['operator'])

        # Adding model 'platter'
        db.create_table(u'platters', (
            ('id', self.gf('django.db.models.fields.IntegerField')(primary_key=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
        ))
        db.send_create_signal(u'afm_viewer', ['platter'])

        # Adding model 'project'
        db.create_table(u'projects', (
            ('id', self.gf('django.db.models.fields.IntegerField')(primary_key=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
        ))
        db.send_create_signal(u'afm_viewer', ['project'])

        # Adding model 'growth'
        db.create_table(u'growths', (
            ('id', self.gf('django.db.models.fields.IntegerField')(primary_key=True)),
            ('growth_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('date', self.gf('django.db.models.fields.DateField')(null=True, blank=True)),
            ('operator', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('chk_pre_rcp', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_pre_openll', self.gf('django.db.models.fields.IntegerField')(null=True, db_column=u'chk_pre_openLL', blank=True)),
            ('chk_pre_load', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_pre_closell', self.gf('django.db.models.fields.IntegerField')(null=True, db_column=u'chk_pre_closeLL', blank=True)),
            ('chk_pre_alk', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_pre_hyd', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_pre_llpres', self.gf('django.db.models.fields.DecimalField')(blank=True, null=True, db_column=u'chk_pre_LLpres', decimal_places=1, max_digits=2)),
            ('chk_pre_opengv', self.gf('django.db.models.fields.IntegerField')(null=True, db_column=u'chk_pre_openGV', blank=True)),
            ('chk_pre_trans', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_pre_rot', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_pre_closegv', self.gf('django.db.models.fields.IntegerField')(null=True, db_column=u'chk_pre_closeGV', blank=True)),
            ('chk_pre_final', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_pre_epi', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_start', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_post_idle', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_post_episave', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_post_opengv', self.gf('django.db.models.fields.IntegerField')(null=True, db_column=u'chk_post_openGV', blank=True)),
            ('chk_post_trans', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('chk_post_closegv', self.gf('django.db.models.fields.IntegerField')(null=True, db_column=u'chk_post_closeGV', blank=True)),
            ('chk_post_llpres', self.gf('django.db.models.fields.DecimalField')(blank=True, null=True, db_column=u'chk_post_LLpres', decimal_places=1, max_digits=2)),
            ('chk_post_openll', self.gf('django.db.models.fields.IntegerField')(null=True, db_column=u'chk_post_openLL', blank=True)),
            ('chk_post_closell', self.gf('django.db.models.fields.IntegerField')(null=True, db_column=u'chk_post_closeLL', blank=True)),
            ('chk_post_alk', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('run_comments', self.gf('django.db.models.fields.CharField')(max_length=1000, blank=True)),
            ('carrier_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p1_sub_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p1_run_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p1_polish', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p2_sub_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p2_run_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p2_polish', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p3_sub_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p3_run_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p3_polish', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p4_sub_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p4_run_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p4_polish', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p5_sub_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p5_run_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p5_polish', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p6_sub_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p6_run_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('p6_polish', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('cl_1', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('cl_2', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('cl_3', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('cl_4', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('cl_5', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('cl_1_laynum', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('cl_2_laynum', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('cl_3_laynum', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('cl_4_laynum', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('cl_5_laynum', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('cl_1_lay_purp', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('cl_2_lay_purp', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('cl_3_lay_purp', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('cl_4_lay_purp', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('cl_5_lay_purp', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('pyro_out_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('pyro_in_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('fil_in_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('fil_out_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('motor_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gc_pres_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gc_pos_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('volt_in_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('curr_in_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('vol_out_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('curr_out_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('vp_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_in_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_out_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_in_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_push_in_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_mid_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_push_mid_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_out_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_push_out_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('n2_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('h2_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('nh3_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_pres_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_pres_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_pres_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_pres_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_pres_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_pres_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2_mg1_pres_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_flow_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_pres_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gr_rate_cl_1', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('pyro_out_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('pyro_in_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('fil_in_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('fil_out_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('motor_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gc_pres_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gc_pos_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('volt_in_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('curr_in_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('volt_out_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('curr_out_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('vp_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_in_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_out_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_in_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_in_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_mid_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_mid_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_out_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_out_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('n2_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('h2_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('nh3_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_pres_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_pres_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_pres_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_pres_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_pres_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_pres_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_pres_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_flow_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_pres_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gr_rate_cl_2', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('pyro_out_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('pyro_in_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('fil_in_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('fil_out_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('motor_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gc_pres_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gc_pos_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('volt_in_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('curr_in_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('volt_out_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('curr_out_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('vp_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_in_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_out_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_in_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_in_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_mid_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_mid_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_out_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_out_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('n2_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('h2_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('nh3_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_pres_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_pres_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_pres_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_pres_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_pres_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_pres_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_pres_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_flow_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_pres_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gr_rate_cl_3', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('pyro_out_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('pyro_in_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('fil_in_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('fil_out_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('motor_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gc_pres_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gc_pos_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('volt_in_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('curr_in_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('volt_out_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('curr_out_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('vp_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_in_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_out_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_in_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_in_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_mid_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_mid_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_out_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_out_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('n2_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('h2_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('nh3_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_pres_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_pres_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_pres_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_pres_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_pres_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_pres_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_pres_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_flow_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_pres_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gr_rate_cl_4', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('pyro_out_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('pyro_in_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('fil_in_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('fil_out_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('motor_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gc_pres_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gc_pos_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('volt_in_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('curr_in_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('volt_out_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('curr_out_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('vp_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_in_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_out_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_in_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_in_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_mid_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_mid_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_flow_out_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('alk_pres_out_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('n2_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('h2_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('nh3_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('hyd_pres_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_pres_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_pres_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_pres_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_pres_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_pres_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_pres_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_flow_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_pres_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('gr_rate_cl_5', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_pre_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_pre_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_pre_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_pre_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_pre_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_pre_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('nh3_pre_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_pre_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_post_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_post_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_post_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_post_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_post_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_post_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('nh3_post_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('sih4_post_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('cp2mg1_temp', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmin1_temp', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga1_temp', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmga2_temp', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tmal1_temp', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('tega1_temp', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=2, blank=True)),
            ('reactor_select', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('layerhas_gan', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('layerhas_algan', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('layerhas_ingan', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('layerhas_aln', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('layerhas_other', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('layeris_ntype', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('layeris_ptype', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('layeris_uid', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('substrate_orient_c', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('substrate_orient_a', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('substrate_orient_m', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('substrateis_orient_r', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('substrate_orient_other', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('is_template', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('substrate_is', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('layerhas_superlattice', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('layerhas_mqw', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('layerhas_sqw', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('project', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('investigation', self.gf('django.db.models.fields.CharField')(max_length=100, blank=True)),
            ('film_orient_c', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('film_orient_a', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('film_orient_m', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('film_orient_r', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('film_orient_other', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
        ))
        db.send_create_signal(u'afm_viewer', ['growth'])

        # Adding model 'afm'
        db.create_table(u'afm', (
            ('id', self.gf('django.db.models.fields.IntegerField')(primary_key=True)),
            ('growth_number', self.gf('django.db.models.fields.CharField')(max_length=45)),
            ('pocket', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('scan_number', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('filename', self.gf('django.db.models.fields.CharField')(max_length=150, blank=True)),
            ('rms', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=3, blank=True)),
            ('zrange', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=3, blank=True)),
            ('location', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('size', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=7, decimal_places=3, blank=True)),
            ('has_amplitude', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('amplitude_filename', self.gf('django.db.models.fields.CharField')(max_length=150, blank=True)),
            ('simple_growth_number', self.gf('django.db.models.fields.CharField')(max_length=45, blank=True)),
            ('webdav_hfile', self.gf('django.db.models.fields.CharField')(max_length=150, blank=True)),
            ('webdav_afile', self.gf('django.db.models.fields.CharField')(max_length=150, blank=True)),
        ))
        db.send_create_signal(u'afm_viewer', ['afm'])


    def backwards(self, orm):
        # Deleting model 'operator'
        db.delete_table(u'operators')

        # Deleting model 'platter'
        db.delete_table(u'platters')

        # Deleting model 'project'
        db.delete_table(u'projects')

        # Deleting model 'growth'
        db.delete_table(u'growths')

        # Deleting model 'afm'
        db.delete_table(u'afm')


    models = {
        u'afm_viewer.afm': {
            'Meta': {'object_name': 'afm', 'db_table': "u'afm'"},
            'amplitude_filename': ('django.db.models.fields.CharField', [], {'max_length': '150', 'blank': 'True'}),
            'filename': ('django.db.models.fields.CharField', [], {'max_length': '150', 'blank': 'True'}),
            'growth_number': ('django.db.models.fields.CharField', [], {'max_length': '45'}),
            'has_amplitude': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'location': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'pocket': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rms': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '3', 'blank': 'True'}),
            'scan_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'simple_growth_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'size': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '3', 'blank': 'True'}),
            'webdav_afile': ('django.db.models.fields.CharField', [], {'max_length': '150', 'blank': 'True'}),
            'webdav_hfile': ('django.db.models.fields.CharField', [], {'max_length': '150', 'blank': 'True'}),
            'zrange': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '3', 'blank': 'True'})
        },
        u'afm_viewer.growth': {
            'Meta': {'object_name': 'growth', 'db_table': "u'growths'"},
            'alk_flow_in_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_in_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_in_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_in_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_in_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_mid_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_mid_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_mid_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_mid_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_mid_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_out_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_out_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_out_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_out_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_flow_out_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_in_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_in_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_in_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_in_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_mid_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_mid_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_mid_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_mid_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_out_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_out_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_out_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_pres_out_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_push_in_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_push_mid_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'alk_push_out_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'carrier_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'chk_post_alk': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_post_closegv': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'db_column': "u'chk_post_closeGV'", 'blank': 'True'}),
            'chk_post_closell': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'db_column': "u'chk_post_closeLL'", 'blank': 'True'}),
            'chk_post_episave': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_post_idle': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_post_llpres': ('django.db.models.fields.DecimalField', [], {'blank': 'True', 'null': 'True', 'db_column': "u'chk_post_LLpres'", 'decimal_places': '1', 'max_digits': '2'}),
            'chk_post_opengv': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'db_column': "u'chk_post_openGV'", 'blank': 'True'}),
            'chk_post_openll': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'db_column': "u'chk_post_openLL'", 'blank': 'True'}),
            'chk_post_trans': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_pre_alk': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_pre_closegv': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'db_column': "u'chk_pre_closeGV'", 'blank': 'True'}),
            'chk_pre_closell': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'db_column': "u'chk_pre_closeLL'", 'blank': 'True'}),
            'chk_pre_epi': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_pre_final': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_pre_hyd': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_pre_llpres': ('django.db.models.fields.DecimalField', [], {'blank': 'True', 'null': 'True', 'db_column': "u'chk_pre_LLpres'", 'decimal_places': '1', 'max_digits': '2'}),
            'chk_pre_load': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_pre_opengv': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'db_column': "u'chk_pre_openGV'", 'blank': 'True'}),
            'chk_pre_openll': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'db_column': "u'chk_pre_openLL'", 'blank': 'True'}),
            'chk_pre_rcp': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_pre_rot': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_pre_trans': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'chk_start': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'cl_1': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'cl_1_lay_purp': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'cl_1_laynum': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'cl_2': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'cl_2_lay_purp': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'cl_2_laynum': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'cl_3': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'cl_3_lay_purp': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'cl_3_laynum': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'cl_4': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'cl_4_lay_purp': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'cl_4_laynum': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'cl_5': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'cl_5_lay_purp': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'cl_5_laynum': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'cp2_mg1_pres_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_post_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_pre_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_pres_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_pres_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_pres_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_pres_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'cp2mg1_temp': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'curr_in_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'curr_in_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'curr_in_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'curr_in_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'curr_in_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'curr_out_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'curr_out_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'curr_out_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'curr_out_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'curr_out_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'fil_in_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'fil_in_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'fil_in_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'fil_in_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'fil_in_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'fil_out_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'fil_out_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'fil_out_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'fil_out_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'fil_out_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'film_orient_a': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'film_orient_c': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'film_orient_m': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'film_orient_other': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'film_orient_r': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'gc_pos_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gc_pos_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gc_pos_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gc_pos_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gc_pos_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gc_pres_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gc_pres_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gc_pres_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gc_pres_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gc_pres_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gr_rate_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gr_rate_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gr_rate_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gr_rate_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'gr_rate_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'growth_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'h2_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'h2_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'h2_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'h2_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'h2_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_in_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_in_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_in_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_in_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_in_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_out_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_out_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_out_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_out_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_out_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_pres_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_pres_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_pres_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_pres_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'hyd_pres_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'investigation': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'is_template': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'layerhas_algan': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'layerhas_aln': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'layerhas_gan': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'layerhas_ingan': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'layerhas_mqw': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'layerhas_other': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'layerhas_sqw': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'layerhas_superlattice': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'layeris_ntype': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'layeris_ptype': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'layeris_uid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'motor_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'motor_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'motor_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'motor_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'motor_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'n2_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'n2_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'n2_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'n2_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'n2_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'nh3_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'nh3_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'nh3_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'nh3_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'nh3_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'nh3_post_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'nh3_pre_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'operator': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p1_polish': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p1_run_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p1_sub_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p2_polish': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p2_run_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p2_sub_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p3_polish': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p3_run_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p3_sub_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p4_polish': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p4_run_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p4_sub_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p5_polish': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p5_run_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p5_sub_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p6_polish': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p6_run_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'p6_sub_number': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'project': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'pyro_in_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'pyro_in_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'pyro_in_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'pyro_in_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'pyro_in_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'pyro_out_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'pyro_out_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'pyro_out_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'pyro_out_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'pyro_out_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'reactor_select': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'run_comments': ('django.db.models.fields.CharField', [], {'max_length': '1000', 'blank': 'True'}),
            'sih4_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_post_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_pre_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_pres_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_pres_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_pres_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_pres_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'sih4_pres_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'substrate_is': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'}),
            'substrate_orient_a': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'substrate_orient_c': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'substrate_orient_m': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'substrate_orient_other': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'substrateis_orient_r': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'tega1_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_post_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_pre_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_pres_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_pres_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_pres_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_pres_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_pres_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tega1_temp': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_post_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_pre_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_pres_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_pres_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_pres_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_pres_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_pres_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmal1_temp': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_post_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_pre_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_pres_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_pres_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_pres_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_pres_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_pres_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga1_temp': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_post_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_pre_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_pres_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_pres_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_pres_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_pres_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_pres_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmga2_temp': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_post_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_pre_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_pres_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_pres_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_pres_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_pres_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_pres_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'tmin1_temp': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'vol_out_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'volt_in_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'volt_in_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'volt_in_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'volt_in_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'volt_in_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'volt_out_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'volt_out_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'volt_out_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'volt_out_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'vp_flow_cl_1': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'vp_flow_cl_2': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'vp_flow_cl_3': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'vp_flow_cl_4': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'}),
            'vp_flow_cl_5': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '7', 'decimal_places': '2', 'blank': 'True'})
        },
        u'afm_viewer.operator': {
            'Meta': {'object_name': 'operator', 'db_table': "u'operators'"},
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'})
        },
        u'afm_viewer.platter': {
            'Meta': {'object_name': 'platter', 'db_table': "u'platters'"},
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'})
        },
        u'afm_viewer.project': {
            'Meta': {'object_name': 'project', 'db_table': "u'projects'"},
            'id': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '45', 'blank': 'True'})
        }
    }

    complete_apps = ['afm_viewer']