# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('d180', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('status_changed', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='status changed')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('growth_length', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('bake_length', models.IntegerField()),
                ('priority', models.BigIntegerField(default=9223372036854775807)),
                ('platter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d180.Platter')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', related_query_name='reservation', to='core.ProcessType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
