# Generated by Django 2.1.5 on 2019-01-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_create_processtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halldata',
            options={'base_manager_name': 'objects'},
        ),
    ]
